language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro
    - WUT_ROOT=/opt/devkitpro/wut
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - PORTLIBREPOS=$HOME/portlibrepos

cache:
  directories:
    - "$HOME/.local"
    - "$DEVKITPRO"

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${PORTLIBREPOS}"
  - mkdir -p "${DEVKITPRO}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb; fi
  - yes | sudo dkp-pacman -Syu devkitPPC --needed
  - wget $(curl -s https://api.github.com/repos/decaf-emu/wut/releases/latest | grep 'browser_' | grep 'linux' | cut -d\" -f4

install:
  - 7z x -y $(ls | grep "linux") -o${WUT_ROOT}
  - cd $PORTLIBREPOS
  - git clone https://github.com/Maschell/libutils.git -b wut
  - cd libutils
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$WUT_ROOT/share/wut.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$WUT_ROOT ../
  - make install
  - cd $PORTLIBREPOS
 
before_script:
  - cd $TRAVIS_BUILD_DIR/
 
script:
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$WUT_ROOT/share/wut.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$WUT_ROOT ../
  - make install